### ISSUE TITLE
Suggestion: Option to only show certain notifications in an overlay

### ISSUE THREAD

**Issue by robuuuste** [KogasaPls/notification-overlay#1]
Hi, I think it would be nice if you could pick what notifications are shown instead of all of them. Maybe it could be done similar to chat notifications plugin? So it only shows the overlay for notifications that match a certain line of text.

**Comment by Jin-Jiyunsun** [comment]
I second this, very cool addon would be great to use for a few notifications only, such as health, prayer.

**Comment by KogasaPls** [comment]
Thanks for the suggestion, sorry it took so long to get around to it!

I implemented this in 881829899f34f7eb2e44ac92c96b001d15ca9afc and submitted a pull request. You can control the visibility and opacity with regex matches now, along with the background color. You can also set the default visibility. Unchecking "Visibility" and adding "show" to your format string will have the desired effect.
