### ISSUE TITLE
New update seems to have broken Duration and Show Time config.

### ISSUE THREAD

**Issue by iatethedinosaurs** [KogasaPls/notification-overlay#2]
Hi, with the newest update it seems the Duration and Show Time configs are no longer respected. The duration starts at 6s regardless of what time is set in the Duration box and the time remaining is always showed despite Show Time being unchecked.

I really appreciate the work you put into this plugin. It makes playing with two accounts that much easier when the notifications are within the game window.

**Comment by KogasaPls** [comment]
Apologies, I'll submit a PR tomorrow with a fix.

**Comment by iatethedinosaurs** [comment]
The latest update was just merged and all seems to be working great! Thank you very much for your work!
