### ISSUE TITLE
Colour of newest notification is applied to all previous notifications?

### ISSUE THREAD

**Issue by crab-pancake** [KogasaPls/notification-overlay#3]
Title, pretty self explanatory. Colour of newest notification overrides colours (custom or default) of all old notifications. 

I've made some edits to the plugin on my end, but I'm pretty sure I haven't touched any of the code for colour. But if this isn't reproducible I guess I broke something without realising.

![javaw_ILJVw7coCA](https://user-images.githubusercontent.com/30866670/231107891-af9dcbbc-bea5-4183-b498-72631387a2db.gif)

**Comment by Raisoshi** [comment]
I have the base plugin, no modifications, same thing is happening to me

**Comment by KogasaPls** [comment]
Fixed in 941f3fbf67a8197575bd043a6051df7efc8c8f56

Merge PR: https://github.com/runelite/plugin-hub/pull/4264
